# Generated by Django 4.2.1 on 2023-06-03 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dizajnapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirwaysPilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airways', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dizajnapp.airways')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dizajnapp.pilot')),
            ],
        ),
    ]
