# Generated by Django 4.2.1 on 2023-06-04 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dizajnapp', '0002_airwayspilot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='photo',
        ),
    ]
