# Generated by Django 4.2.1 on 2023-07-02 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dizajnapp', '0005_alter_flight_ballon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='ballon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dizajnapp.ballon'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='flights/'),
        ),
    ]
